# Generated by Django 6.0.5 on 2026-06-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('credits', models.IntegerField(default=3)),
                ('coefficient', models.FloatField(default=1.0)),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_cc', models.FloatField(blank=True, null=True, verbose_name='Contrôle Continu')),
                ('note_tp', models.FloatField(blank=True, null=True, verbose_name='Travaux Pratiques')),
                ('note_exam', models.FloatField(blank=True, null=True, verbose_name='Examen')),
                ('moyenne', models.FloatField(blank=True, null=True, verbose_name='Moyenne')),
                ('semestre', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2')], default='S1', max_length=10)),
                ('annee_academique', models.CharField(default='2025-2026', max_length=9)),
                ('valide', models.BooleanField(default=False)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
    ]
