# Generated by Django 6.0.5 on 2026-06-10 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='note_cc',
        ),
        migrations.RemoveField(
            model_name='note',
            name='note_tp',
        ),
    ]
